// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmwgpE1veOHUqmNcOrhGv9FtGW7JXcUQ',
    appId: '1:535217593599:web:cc6510a31f58f0103780ca',
    messagingSenderId: '535217593599',
    projectId: 'polls-b3204',
    authDomain: 'polls-b3204.firebaseapp.com',
    storageBucket: 'polls-b3204.appspot.com',
    measurementId: 'G-QTNMQ5QRGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFtYATMLUp-T0lYEIDEbNPA9YMs8J5ys',
    appId: '1:535217593599:android:251dab9d757d9cc03780ca',
    messagingSenderId: '535217593599',
    projectId: 'polls-b3204',
    storageBucket: 'polls-b3204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ENEKaamATlvqzHb4QSqff_5543Xs2MU',
    appId: '1:535217593599:ios:ae1aa0fd8a3dca533780ca',
    messagingSenderId: '535217593599',
    projectId: 'polls-b3204',
    storageBucket: 'polls-b3204.appspot.com',
    iosClientId: '535217593599-h7t2tvb36nd2kst1ed2fl4nukiflr5i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPolls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ENEKaamATlvqzHb4QSqff_5543Xs2MU',
    appId: '1:535217593599:ios:ae1aa0fd8a3dca533780ca',
    messagingSenderId: '535217593599',
    projectId: 'polls-b3204',
    storageBucket: 'polls-b3204.appspot.com',
    iosClientId: '535217593599-h7t2tvb36nd2kst1ed2fl4nukiflr5i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPolls',
  );
}
